### ISSUE TITLE
Access to /opt is not blacklisted

### ISSUE THREAD

**Issue by saildata** [pigmonkey/firewarden#1]
Steps to reproduce:
1. `firewarden firefox`
2. Navigate to `file:///`
3. Select /opt

Actual results:
The contents are readable

Expected results:
Directory contents are blacklisted

**Comment by pigmonkey** [comment]
Firejail does not currently support a private `/opt`, so we can't do anything about this here. I reported it upstream as netblue30/firejail#914.

**Comment by saildata** [comment]
Thanks for the quick reply! The only workaround I came up with was to copy the output of `for file in $( ls /opt ); do echo blacklist opt\/$file; done`
