### ISSUE TITLE
Does not work in Void linux ?

### ISSUE THREAD

**Issue by ghost** [pigmonkey/firewarden#2]
Hi @pigmonkey ! 
This morning I noticed your [package](https://aur.archlinux.org/packages/firewarden/) in AUR. 
It sounded interesting, so I decided to create a new package for Void linux, see [here](https://forum.voidlinux.eu/t/firewarden-fire/2741), but something is wrong when I run your script... 
I'm not very experienced in packaging, but I try to learn, so your help will be very appreciated! :wink: 

Regards.

**Comment by pigmonkey** [comment]
Your link to the Void forums is timing out for me. Can you explain here what problem you're experiencing?

**Comment by ghost** [comment]
See this very short [log](https://gist.github.com/cr6git/2d1474772e983094e7c6cd79c9cbe92f) for example. 

"Warning: cannot find /var/run/utmp" => certainly because it's "/run/utmp" in Void. 

Void linux is _a little different_ from the other distros. 
For exemple Void uses glibc and [musl](https://www.musl-libc.org/intro.html), and musl is very strict regarding scripts & POSIX.

**Comment by pigmonkey** [comment]
So it looks like the script is executing Firejail successfully, which is all it is supposed to do, but then Firejail fails. Try launching viewnior like this:

    $ /usr/bin/firejail --private-srv=firewarden/2017-06-04T11:17:09-07:00 --private-opt=firewarden/2017-06-04T11:17:09-07:00 --private viewnior

That is essentially what firewarden does when you call `firewarden viewnior`. I'm guessing it fails in the same way.

If that fails, try it without the `--private-srv` and `--private-opt` flags (which were just introduced in Firejail 0.9.46).

**Comment by ghost** [comment]
`$ /usr/bin/firejail --private-srv=firewarden --private-opt=firewarden --private viewnior`

This command fails, as in my first example, see the [log](https://gist.github.com/cr6git/10df3b9b9a9a1f7b725eea34f1bd6a77).

Now, without the `--private-srv` and `--private-opt` flags:

`$ /usr/bin/firejail --private viewnior`

It seems to be working ! :smiley:

**Comment by pigmonkey** [comment]
Ok. You should report the issue with `--private-srv` and `--private-opt` on Firejail's issue tracker.

**Comment by ghost** [comment]
Thanks for the help, @pigmonkey 

We could close this issue, then ?
