### ISSUE TITLE
invalid --private-srv ... commandline option

### ISSUE THREAD

**Issue by glennlopez** [pigmonkey/firewarden#4]
"Installed" (gitcloned) on Ubuntu 16.04 LTS
placed firewarden script on /usr/bin/ and /usr/local/bin/
ran $ firewarden firefox
got an invalid --private-srv error
ran $ firewarden firefox http://google.com
got an invalid --private-srv error
ran $ sudo firewarden firefox
got an invalid --private-srv error

how to fix this?

**Comment by pigmonkey** [comment]
You closed this, so I imagine you've identified the issue, but in case anybody else comes across this:

Ubuntu 16.04 LTS ships an old version of Firejail that does not support the `--private-srv` flag. I'd accept a pull request for some sort of version detection, but it seems simpler to upgrade firejail. I imagine there is a PPA that providers the latest release to older LTS installs.
